### ISSUE TITLE
building problems in windows

### ISSUE THREAD

**Issue by darck-neos** [Hopson97/MineCraft-One-Week-Challenge#125] opened 2018-11-07 06:11 UTC
Hi @Hopson97,

I start by mentioning that I have no problems running the versions on Windows but yes in Linux. I found these versions with an .exe file on your video:
https://drive.google.com/file/d/0B-bhEaACRE65ZU5YSkZnU0RPZEE/view
https://drive.google.com/file/d/0B-bhEaACRE65WF8ydkROS1hEMTg/view

and suddenly I found this version:
https://github.com/Hopson97/MineCraft-One-Week-Challenge/tree/aa50ad8077ef0e617a9cfc336bdb7db81c313017

The last version doesn't have a version with an .exe file for Windows and there is when my problems started. I couldn't find a way to build your code in windows, you put that is necessary GLM and SFML 2.4.1+ libraries w/headers but when I tried to install SFML I just found it: https://www.sfml-dev.org/download/sfml/2.5.1/
There is only .zip versions for Visual C++ or MinGW but I couldn't overcome that. I download a zip an after that? What I need to do in order to configure the tools for just write "make" and generate the .exe file with the help of the MakeFile in the version with shaders? I viewed https://github.com/Hopson97/MineCraft-One-Week-Challenge/issues/74 but I couldn't understand how to do those steps because I can't or don't know how to add the repository.

I even install ubuntu just to use your command "sudo apt-get install libsfml-dev libglew-dev libglm-dev" and then I could build your project (even old versions) but when I execute the program there is black screen (in ubuntu). My goal is to make changes and add features based on your code but my principal problem is build your code. If I achieve to build your code with the makefile I will be very happy because I will be able to start making changes even with a notepad and re-build with the makefile. I would prefer open your project in Code::Blocks but I don't know how to configure my environment to start to program and when I try to open the folder "MineCraft-One-Week-Challenge-aa50ad8077ef0e617a9cfc336bdb7db81c313017" in Code::Blocks there is no results, is waiting for a file. I don't know how to open that folder in Code::Blocks in order to have an environment like your video https://www.youtube.com/watch?v=Xq3isov6mZ8 or what to do in the Workspace to have a project like yours with Sources, Headers and Others because I watch in your video the same folders that are in the github like Item, GL, Res, Shaders but I can't overcome this problem.

I have practiced and learned OpenGL but with very different tools and now I don't know how to use Code::Blocks or build your project with SFML. At least, I will be very grateful if you put a download link of the version with shaders with an .exe file but I prefer to overcome my configuration problem and start to develop like all the people involved in this project.

**Comment by Hopson97** [comment] 2018-11-07 07:55
https://github.com/Hopson97/MineCraft-One-Week-Challenge/releases

In the releases folder, there is a zip folder with a exe

**Comment by Hopson97** [comment] 2018-11-07 07:56
The latest version should have the black screen issue fixed (works for me on Ubuntu)

**Comment by Hopson97** [comment] 2018-11-07 08:24
This was caused by GLM making some changes to the library where their data types no longer default initialized to 0, so you have to go through the code and do {0.0f, 0.0f, 0.0f} for every declaration of a `glm::vec3` and `{0.0f}` for every declaration of a mat4

After this, the black screen should be fixed.

**Comment by darck-neos** [comment] 2018-11-07 19:24
I viewed the folder with the .exe but that doesn't seem to be the version with day/night cycle. The black screen disappear with your comment but for some issues I had to format my computer and use only Windows, there is a method to build in Windows?

**Comment by darck-neos** [comment] 2018-11-07 20:59
I was watching your .gitignore and found;

#CodeBLocks stuff
*.layout
*.depend
*.cbp
bin/
obj/

#Makefile stuff
*.o
MinecraftWeek

#.dll stuff
*.dll

#Builds
*.7z
Project/

#Profiler
*.out

#Visual Studio
.vscode/

#exe
*.exe
MinecraftWeek/

#Mac stuff
*.DS_STORE

#CMakeCache file
CMakeCache.txt

I think that those files help to load the project, I cannot add the repository in Code::Blocks to proceed to link SFML and other libraries. Could you upload a version for Windows without ignore some of those files that helps Code::Blocks to load the project or a video in your channel explaining how to build the project downloading from github?

The make command give me the follow error:
![image](https://user-images.githubusercontent.com/44827734/75093023-005a1300-554c-11ea-9788-1acbde212f0d.png)

**Comment by kennyrkun** [comment] 2018-11-07 22:13
Those files should not be included in the repository, thus the .gitignore is correct.

The repository downloaded as a zip from the main page includes exactly what is needed to build and run the program on Windows (I used Visual Studio, and it took me all of five minutes to download and build.)

**Comment by darck-neos** [comment] 2018-11-09 02:27
In that case, could you help me to build in Visual Studio?. I have little expertise with the tools you use, if you can configure and build in 5 minutes then you know what to do but other people like me not, it seems some people have problems to build the project on windows (the issues history) because of ignorance. I was asking for the .gitignore to open in Code::Blocks, but if possible to open and build in other IDE like Visual Studio then help me, please.

**Comment by Hopson97** [comment] 2018-11-09 08:42
Simplest way:

1. You need to set up SFML in a Visual studio project: https://www.sfml-dev.org/tutorials/2.5/start-vc.php

2. Download GLM and unzip it somewhere: https://glm.g-truc.net/0.9.9/index.html

3. Set up your VS  project to have the glm/glm folder as an include directory

4. Copy paste every file from this repo to the VS project folder.

5. Hope it works :S

**Comment by darck-neos** [comment] 2018-11-16 23:28
Bad news, it doesn't work :(

![image](https://user-images.githubusercontent.com/44827734/75093305-5d56c880-554e-11ea-83a1-cddb52bd88fe.png)

**Comment by darck-neos** [comment] 2018-11-17 00:57
I tried to load the project of the first day adding everything and I obtain these errors:

![image](https://user-images.githubusercontent.com/44827734/75093420-9e031180-554f-11ea-810b-bdf3d4f030c4.png)

I search and found this macro:

#ifndef _MSC_VER
#define NOEXCEPT noexcept
#else
#define NOEXCEPT
#endif

Then I added that on all files with the problem. Also I modify this:

![image](https://user-images.githubusercontent.com/44827734/75093441-bd01a380-554f-11ea-9f38-af320594da97.png)

for:

![image](https://user-images.githubusercontent.com/44827734/75093448-d145a080-554f-11ea-961b-e5788f61f8f7.png)

and finally I could compile the project. Also, I copy the folders Res and Shaders in the file Debug and in the file with the same name of the project in order to execute the .exe (in Debug) and use Local Windows Debugger of Visual Studio and obtain this result:

![image](https://user-images.githubusercontent.com/44827734/75093459-e4587080-554f-11ea-8e08-3c057881d291.png)

Now, I will try with other new projects and update here if I could build successfully!!

**Comment by darck-neos** [comment] 2018-11-23 01:26
Hello again @Hopson97, finally I understand how to build this project. For that reason, I will write how to build the project.

I downloaded the version with day/night cycle and follow the steps you put comments above and then I proceeded apllying the macro for the noexcept errors:

#ifndef _MSC_VER
#define NOEXCEPT noexcept
#else
#define NOEXCEPT
#endif

Suddenly, I found and error for "constexpr" and everything was clear, the problem was the version of Visual Studio I used that had problems with the compiler that supports c++ 14 but not with SFML or GLM. I just changed the version to **Visual Studio 2017**, configure SFML and GLM, copy the files of the repo to the project and add the all source code files (.cpp) and header files (.h) including the ones inside the folders. After that, I build the project without modifying nothing like noexcept or constexpr and it worked. I hope anyone who read this issue know how to build the project. It was only necessary to change the version of the IDE I used. I can say that the issue was solved, hope @kennyrkun doesn't continue confused, maybe this little and simple detail (the version of the IDE) confuse people that try to build the project in Windows, thanks for all

**Comment by kennyrkun** [comment] 2018-12-14 03:35
@Hopson97 this issue was solved.

**Closed as completed** 2018-12-14 09:41 UTC
